module.exports = {
    mongoURI:process.env.MONGO_URI,
    mqttURL: process.env.MQTT_URL,
    mqttID: process.env.MQTT_USER,
    mqttPW: process.env.MQTT_PASS,
    divisionIdx: process.env.DIVISION_IDX,
    deviceIdx: process.env.DEVICE_IDX,
    restApi: process.env.REST_API,
    userId: process.env.USER_ID,
    userPassword: process.env.USER_PASSWORD,
    jwtToken: process.env.JWT_TOKEN,
    minioAccessKey: process.env.MINIO_ACCESS_KEY,
    minioSecretKey: process.env.MINIO_SECRET_KEY,
    minioURL: process.env.MINIO_URL,
    sensorAPI: process.env.SENSOR_API,
    // 서비스 API 설정
    ioboardApi: process.env.IO_BOARD_URL || 'http://localhost:8000',
    deadboltApi: process.env.DEADBOLT_URL || process.env.IO_BOARD_URL || 'http://localhost:8000',
    cameraApi: process.env.CAMERA_API || 'http://localhost:8003',
    cardTerminalApi: process.env.CARD_TERMINAL_API || 'http://localhost:8001',
    modelApi: process.env.MODEL_API || 'http://localhost:8002',
}
